### ISSUE TITLE
Support for many databases as cache data store / SQLAlchemy engine 

### ISSUE THREAD

**Issue by femtotrader** [ionrock/cachecontrol#97]
Hello,

it will be nice if a connection to SQLAlchemy (engine) could be pass to cachecontrol (maybe using cache argument).
see http://docs.sqlalchemy.org/en/rel_0_9/core/engines.html

It will provide more DB support (MySQL, PostgreSQL, Oracle, Microsoft SQL Server...)

Pandas is doing something similar:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.sql.read_sql.html

APSScheduler also
https://apscheduler.readthedocs.org/en/latest/

`cache` argument could be

- a `SQLAlchemyCache` object
- a SQLAlchemy `engine`
- a database URI like `dialect+driver://username:password@host:port/database`
- a table URI like `dialect+driver://username:password@host:port/database::tablename`

    from cachecontrol.caches import SQLAlchemyCache

Kind regards

**Comment by ionrock** [comment]
@femtotrader This is a great idea, but I'm not planning on adding any other cache backends to CacheControl. That said, if you implement a cache backend as you describe, please let me know and I'll link to it in the documentation. 

The reason being is that Python packaging can be problematic at times when you have functionality that is only supported when certain packages are installed. It is not impossible, but generally, it is easier on the user to just install something like "cachecontrol-sqlalchemy" in a requirements.txt or in a setup.py. Also, I'd like to avoid being a bottleneck on any interesting backends as I don't have time to work on ones that I won't be using. 

If you do try to implement this (I don't think it would be terribly difficult) and need any help, please don't hesitate to get in touch. Also, please let me know if you do get things up and working as I'd love to spread the word!

Thanks!

**Comment by scollinson** [comment]
@ionrock are you still opposed to a PR for this? I have implemented and tested a SQLAlchemy cache backend, so can submit as a PR or create my own package.

**Comment by ionrock** [comment]
@scollinson I'm still not going to add any new cache backends, but please send a PR for the docs including links to your storage backend! I'll also do a new a release to ensure folks take a look.
